---

# Update repositories cache if older than 3600s
- name: "Update APT package cache if stale"
  apt: update_cache=yes cache_valid_time=3600
  tags:
    - apt

- name: "Install Development tools"
  apt: pkg=${item} state=installed
  with_items:
    - htop
    - bar
    - nmap
    - mtr-tiny
    - git
  tags:
    - apt
